services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: .
          target: /src
  db:
    image: postgres:latest
    ports:
      - "5432:5432"