services:
  web:
    build: .
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    develop:
      watch:
        - action: sync
          path: .
          target: /src
    environment:
      - JWT_SECRET=jwtsecretkey
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
